language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - rm -rf ./node_modules
  - yarn install

script:
  - yarn run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sunnyharoro/timecapsreact:latest .
  - docker push sunnyharoro/timecapsreact:latest
